name: Sync packages

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 1 * *' # 每月 1 日自动触发一次

jobs:
  sync-packages:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出目标仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整历史记录以便提交更改

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gitpython

      # 4. 运行同步脚本
      - name: Run sync script
        run: |
          python sync_packages.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. 提交并推送更改
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated sync of packages"
          git push origin main
