name: Sync packages from repositories

on:
  workflow_dispatch: # 手动触发
  push: # 或者在特定分支推送时触发
    branches:
      - main

jobs:
  sync-packages:
    runs-on: ubuntu-latest

    steps:
      # 检出主仓库
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      # 安装 Python 和依赖
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 运行 Python 脚本同步仓库
      - name: Run Python script to sync repositories
        run: |
          python sync_packages.py

      # 配置 Git 凭据并提交更改
      - name: Configure Git and commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # 使用 GITHUB_TOKEN 配置身份验证
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # 提交更改
          git add .
          git commit -m "Sync packages from repositories" || echo "No changes to commit"
          git push
